	spring.datasource.url=jdbc:postgresql://dpg-d8nro6bsq97s73bo9ljg-a.oregon-postgres.render.com:5432/configmanager
	
	spring.datasource.username=postgres_user
	
	spring.datasource.password=7P35q3IXOpuFQBDTMzV5MgLrtrOxmn4W
	
	spring.datasource.driver-class-name=org.postgresql.Driver
	
	spring.jpa.hibernate.ddl-auto=update
	
	spring.jpa.show-sql=true
	
	spring.jpa.properties.hibernate.format_sql=true
	
	spring.sql.init.mode=always
	spring.jpa.defer-datasource-initialization=true
	server.port=${PORT:8080}